### ISSUE TITLE
Change username to identity

### ISSUE THREAD

**Issue by geerteltink** [zendframework/zend-expressive-authentication#14]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-authentication/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-authentication/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I'm trying to implement this in a system that doesn't have unique usernames (only real names). It has userId's and unique email addresses though. However implementing the UserInterface with getUsername() doesn't make sense if it returns the id or email address.

To me it makes more sense to have something less strict like this:
```php
interface UserInterface
{
    /**
     * Get the unique user identity (id, username, email address or ...)
     */
    public function getIdentity() : string;

    /**
     * Get all user roles
     *
     * @return string[]
     */
    public function getUserRoles() : array;
}
```

**Comment by ezimuel** [comment]
@xtreamwayz I think your proposal makes sense. I'll provide a PR for that soon. Thanks!
