### ISSUE TITLE
Make UserInterface::getIdentity() return an array

### ISSUE THREAD

**Issue by geerteltink** [zendframework/zend-expressive-authentication#24]
I've been having issues with the UserInterface. For the current application I'd like to have the ID, email address and name available. However for some other applications I only want a username. So in other words, the userinterface is pretty limited. 

If we change the getIdentity method to an array or maybe add an extra getSessionAttributes() method to return an array with extra attributes, it would make it a lot more flexible.

```php
public function getSessionAttributes() : array
{
    return [
        'id' => $this->id,
        'name' => $this->name,
        'email' => $this->email,
        'username' => $this->username,
    ];
}
```

**Comment by weierophinney** [comment]
Should it be `getSessionAttributes()` or `getIdentityAttributes()`/`getIdentityData()`/whatever?

Either way, yes, this would definitely be helpful; I had a similar thought when implementing an OAuth2 client adapter, as I end up with only the authenticated username, but no additional data that I might want to use.
