### ISSUE TITLE
Use iterable instead of array?

### ISSUE THREAD

**Issue by internalsystemerror** [zendframework/zend-expressive-authentication#26]
https://github.com/zendframework/zend-expressive-authentication/blob/2fea5529d78cddc26921e46e87ea886ccb8cc7d1/src/UserInterface.php#L24

I'm looking to implement RBAC and DoctrineORM with this, changing the return type to iterable instead of array would allow the use of a Collection (of RoleInterface's). 7.1 is the minimum version of this component.

Any problems with this approach? I wanted to ask before just submitting a PR.

**Comment by geerteltink** [comment]
Works for me.

**Comment by ezimuel** [comment]
Fixed in #27
