### ISSUE TITLE
Proposal to remove UserRepositoryInterface::getRolesFromUser()

### ISSUE THREAD

**Issue by geerteltink** [zendframework/zend-expressive-authentication#29]
https://github.com/zendframework/zend-expressive-authentication/blob/2fea5529d78cddc26921e46e87ea886ccb8cc7d1/src/UserRepositoryInterface.php#L29

I'm wondering why that is added to the interface. Since the roles are added to an authenticated user, it's only needed internally to retrieve the roles in certain situations. E.g. the included PdoDatabase Repository uses it. But if you use doctrine and have the roles added as a relation, it's already included for you. Also Htpasswd  doesn't have roles.

Also the authorization module doesn't use it as it gets the roles from the User object.

**Comment by ezimuel** [comment]
Fixed in #28.
