### ISSUE TITLE
AuthenticationMiddleware does not work correctly when last in pipe chain. Cannot distinguish successful vs failed auth attempt.

### ISSUE THREAD

**Issue by alextech** [zendframework/zend-expressive-authentication#32]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-authentication/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-authentication/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

A typical usage for authentication process is having `AuthenticationMiddleware` at the end of a login route/pipeline:

```php
$app->route('/login', [
  \App\Handler\LoginHandler::class,
  \Zend\Expressive\Authentication\AuthenticationMiddleware::class
]);
```

where LoginHandler performs authentication process by 
```php
$this->loginForm->setData($request->getParsedBody());
if ($this->loginForm->isValid()) {
   $response = $handler->handle($request);
      if ($response->getStatusCode() !== 302) {
         return new RedirectResponse('/');
      }

   $error = 'Login Failure, please try again';
} 
// return html response with login form
```

Because it is last, `return $handler->handle()` in `AuthenticationMiddleware` always returns 404, causing the entire error handling template to be rendered and immediately discarded. I discovered this when for longest I couldn't tell why some code in my 404 template kept on crashing at least expected times... And of course unnecessary performance problem.

### Expected results

- Authentication adapter not cause unexpected error handling stack to execute, not assume there will always be another handler after it.
- If there is another handler (eg. to control myself the redirect process), may need to know **why** 302 was caused. Perhaps `AuthenticationResult` needs to be returned instead of letting `PhpSession` run out of control?

### Actual results
- error templates rendered unexpectedly
- Unable to differentiate whether 302 was caused by successful login, failed authorization, or log-out process to get around.

**Comment by geerteltink** [comment]
> Authentication adapter not cause unexpected error handling stack to execute, not assume there will always be another handler after it.

AFAIK there should always be at least 1 handler after it: the NotFoundHandler or something similar. It's the whole principle of the expressive middleware pipeline. It starts with the ErrorHandler and ends with the NotFoundHandler.

I'm not sure if there are any use cases for adding extra middleware after the AuthenticationMiddleware, if not, a solution could be to return a new Response with the user object.

> I couldn't tell why some code in my 404 template kept on crashing at least expected times.

Easiest solution: fix the code in the 404 template so it doesn't crash. You might need to pre-populate the renderer with some frequently used data to get it working. Although I don't see how this situation should be any different then an invalid URL. I mean if a specific URL is not found by the router, you trigger a 404 as well, which has only the bare minimum data loaded for rendering. Did you forget to add some middleware that is needed to render a 404 page?

> error templates rendered unexpectedly

There is a difference between the templates. There is a 404 template which should be called with how it's coded right now. And it sounds like an exception, while rendering your 404 template, caused triggering the  error template.

> Unable to differentiate whether 302 was caused by successful login, failed authorization, or log-out process to get around.

A 302 is always caused by a failed authorization.
A successful login returns a 404 response with the user object (I know, it's not very logical). 
Logout is something else, at least how I did it:

```php
class LogoutHandler implements RequestHandlerInterface
{
    public function handle(ServerRequestInterface $request) : ResponseInterface
    {
        /** @var SessionInterface $session */
        $session = $request->getAttribute(SessionMiddleware::SESSION_ATTRIBUTE);
        if ($session->has(UserInterface::class)) {
            $session->clear();
        }

        return new RedirectResponse('/');
    }
}
```

**Comment by alextech** [comment]
> AFAIK there should always be at least 1 handler after it: the NotFoundHandler or something similar

I see... So at minimum I should have

```php
$app->route('/login', [
  \App\Handler\LoginHandler::class,
  \Zend\Expressive\Authentication\AuthenticationMiddleware::class
  //RedirectOnSuccessMiddleware ?
]);
```
?
>Easiest solution: fix the code in the 404 template so it doesn't crash.

Problem here is unexpected rendering. (1) It is negative development experience when working on login action, yet the code ends up at NotFoundHandler for **no** reason because */login* **is** a valid URL.  (2) that is unnecessary performance problem to always be rendering 404 even for valid requests. Usage popularized by @samsonasik tutorial causes those error handlers to run at all times, I guess because the fact that `AuthenticationMiddleware` "should always have 1 handler after it" is not evident.

>A 302 is always caused by a failed authorization.

and

>if not, a solution could be to return a new Response with the user object

So if AuthenticationMiddleware already does this, then having another handler after it just to avoid error handlers from running *and* not returning `RedirectResponse` because even a successful login redirection still returns 302 from `LoginHandler` perspective,  seems redundant:

```php
$app->route('/login', [
   \App\Handler\LoginHandler::class,
   \Zend\Expressive\Authentication\AuthenticationMiddleware::class,
   function(\Psr\Http\Message\ServerRequestInterface $request) {
      // cannot do RedirectResponse('/h/:id') because LoginHandler wont distinguish between
     // 302 by auth's failure or this callback's success, 
     // unless success RedirectResponse should have some other 3xx code?
       return new Zend\Diactoros\Response\EmptyResponse($request->getAttribute(\Zend\Expressive\Authentication\UserInterface::class))
}

```

`LoginHandler` is expecting to know the difference to either re-display form with error from authentication, or let the redirection carry on, which was very easy to do in Z\Authentication 2.5

**Comment by weierophinney** [comment]
@alextech —

You are operating on a false premise.

The design of this middleware, as well as the authorization middleware, is such that the recommended use case is within _path-specific_ or _route-specific_ pipelines, and specifically NOT for use as the last middleware in a pipeline. They are both intended to intercept access to later middleware/handlers in cases of invalid or missing credentials/roles.

Why?

The first time through, you will not be authenticated, and will be prompted for credentials (or redirected to a page where you can provide them).

The second and later times through, your request will contain some form or authentication token indicating a valid user. This may be something like an OAuth2 Bearer token, or session data. In those cases, the authentication middleware _still needs to verify this data_. In the case of OAuth2, the token may be invalid (tampered with) or expired. In the case of a session, the session may have expired. In those cases, the middleware can present an "unauthorized response", generally either re-displaying a login form or redirecting to one.

As such, you will compose the middleware in one of the following ways:

- Via path-based middleware. In this example, we're saying everything under the path `/admin` needs authentication:

  ```php
  $app->pipe('/admin', [
      SessionMiddleware::class,
      AuthenticationMiddleware::class,
  ]);
  ```

- Via route-based middleware. In this particular case, we're saying that `POST` requests to `/api/books` require an authenticated user:

  ```php
  $app->post('/api/books', [
      SessionMiddleware::class,
      AuthenticationMiddleware::class,
      CreateBookHandler::class,
  ]);
  ```

The `AuthenticationMiddleware` is expressly NOT intended to be the last item in a pipeline, as it is _guarding_ later middleware from _unauthenticated usage_.
