### ISSUE TITLE
Readme: still not meant for production?

### ISSUE THREAD

**Issue by steffenbrand** [zendframework/zend-expressive-authentication#35]
I was wondering if this is still not meant to be used in production, since there haven't been any big code changes in the last 3 months.

I'm planning to use this middleware for two projects.
I haven't experienced anything that's preventing me to use this in production, except your hint in the readme.

(And the fact, that I'm getting my head ripped off, I there are errors and they find out I have been warned.)

**Comment by weierophinney** [comment]
@steffenbrand We're actually planning on tagging 1.0 of this this week, and gradually releasing stable releases of the various adapters.

The adapters were the main reason we've not tagged a stable version. In the past, we've made some API changes to this repository based on the needs different adapters presented, and having pre-release versioning has allowed us to do so without needing new major releases. At this time, however, it looks like all the possible use cases we anticipate are met by the current API, allowing us to tag the stable version.

**Comment by steffenbrand** [comment]
Thanks for the info, I really appreciate the work you guys are doing.
