### ISSUE TITLE
Unable to extend PdoDatabase user repository implementation

### ISSUE THREAD

**Issue by marcguyer** [zendframework/zend-expressive-authentication#38]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-authentication/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-authentication/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Continued from [slack](https://zendframework.slack.com/archives/C4RF57B0E/p1539092826000100)...

I'd like to extend [UserRepository\PdoDatabase](https://github.com/zendframework/zend-expressive-authentication/blob/master/src/UserRepository/PdoDatabase.php) since the `password_verify` function does not meet our needs for legacy password hash verification.

Additionally, we have a flag in the db for a user to indicate whether the user is "active". We'd like to return `null` in the event that the user is not "active".

### Code to reproduce the issue

```php
namespace MyNamespace;

use Zend\Expressive\Authentication\UserRepository\PdoDatabase;
use Zend\Expressive\Authentication\UserInterface;

class MyUserRepository extends PdoDatabase
{

    public function authenticate(string $credential, string $password = null): ?UserInterface
    {
        // do anything with $this->config
        var_dump($this->config);
    }
}
```

### Expected results

I expect to be able to access `$this->config` property (as well as `$this->pdo` and `$this->userFactory`) in an extension.

### Actual results

> Undefined property: MyNamespace\\MyUserRepository::$config

**Comment by ezimuel** [comment]
@marcguyer are you sure you need to extend `PdoDatabase` instead of proposing a custom `UserRepositoryInterface` implementation? If you have to change the `authenticate()` function logic and you have also extra attribute like `active` it sounds more likely a new repository implementation.

**Comment by kachar** [comment]
In similar use case we've implemented the `UserRepositoryInterface` and replaced in the configuration aliases as follows:

```php
use Zend\Expressive\Authentication\UserInterface;
use Zend\Expressive\Authentication\UserRepositoryInterface;
use Zend\Expressive\Authentication\UserRepository\UserTrait;

class ApikeyRepository implements UserRepositoryInterface
{
    use UserTrait;

    public function authenticate(string $credential, string $password = null) : ?UserInterface
    {
    }

    public function getRolesFromUser(string $identity) : array;
    {
    }
}
```

```php
'aliases' => [
    UserRepositoryInterface::class => ApikeyRepository::class,
],
```

**Comment by ezimuel** [comment]
@kachar the idea is good but be careful, we removed `UserTrait` starting from `zend-expressive-authentication` v. 0.5.0.

**Comment by kachar** [comment]
@ezimuel ah, yes indeed, thanks for the insight. Just updated the to latest implementation.
In the 1.0.0 version the code is much more simpler and easy to use.

For the sake of the example..
```php
use Zend\Expressive\Authentication\UserInterface;
use Zend\Expressive\Authentication\DefaultUser;
use Zend\Expressive\Authentication\UserRepositoryInterface;

class ApikeyRepository implements UserRepositoryInterface
{
    public function authenticate(string $credential, string $password = null): ?UserInterface
    {
        return new DefaultUser();
    }
}
```

**Comment by marcguyer** [comment]
> are you sure you need to extend PdoDatabase instead of proposing a custom UserRepositoryInterface implementation?

No, I don't *need* to extend it, but since I can't, my concrete implementation of `UserRepositoryInterface` must also redefine the other methods of `PdoDatabase`. It's not a big deal, just an inconvenience. 

In my particular case, it's really not a big deal since I need to implement several interfaces for the user repository anyway.

**Comment by ezimuel** [comment]
@marcguyer Ok, I'm closing the issue.
