### ISSUE TITLE
If i can - Authexpressive

### ISSUE THREAD

**Issue by lpj145** [zendframework/zend-expressive-authentication#8]
Sorry for this issue, i liked so much about expressive implementation, and make some packages to expressive, you can found this list:
https://github.com/lpj145?tab=repositories

And one of all, i make agnostic database and have two interfaces for all functionality package.
https://github.com/lpj145/AuthExpressive
fault only rules.
This is for token ( jwt ).

**Comment by lpj145** [comment]
After install define two interface on service manager

StoraInterface
DatabaseInterface

He have some controllers:
LoginController
MeController
RegisterController
RememberTokenController
UpdateMeController

Middleware:
JwtMiddleware -> Verify and authentic user
MeMiddleware -> pass atribute about user logged, this info request on StorageInterface.

**Comment by froschdesign** [comment]
Please use the [forum](https://discourse.zendframework.com/) or [Slack](https://zendframework-slack.herokuapp.com) for this topic.
